OnlineCarRentalSystem/OnlineCarRentalSystem/Controllers/AdminController.cs
using OnlineCarRentalSystem.Models;
using OnlineCarRentalSystem.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineCarRentalSystem.Controllers
{
    public class AdminController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        /*******************************************************************************************/
        public ActionResult retrieve_users(int user_role_id)
        {
            var roles_db = db.Roles.Where(q => q.id != 1).ToList();
            var users_db = db.Users.ToList();
            var historyofblock_db = db.History_OfBlock.ToList();
            var customers_db = db.Customers.ToList();

            if (user_role_id == 2)
            {
                users_db = db.Users.Where(q => q.RoleTypeId == 3).ToList();
                roles_db = db.Roles.Where(q => q.id == 3).ToList();
            }

            UsersRoles ucr = new UsersRoles
            {
                users = users_db,
                customers = customers_db,
                roles = roles_db,
                historyofblock = historyofblock_db
            };
            return View(ucr);
        }
        /************************************************************************************************/
        [HttpPost]
        public ActionResult editCustomerAccount(int user_id,int addtionalAccount)
        {
            var result = 0;
            var customer_selected = db.Customers.SingleOrDefault(x => x.userId == user_id);
           if (customer_selected != null)
            {
               
                   customer_selected.account += addtionalAccount;
               
                db.SaveChanges();
                if (Session["UserRoleId"].Equals(1))
                {
                    result = 1;
                }
                else if (Session["UserRoleId"].Equals(2))
                {
                    result = 2;
                }
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        /************************************************************************************************/
        [HttpPost]
        public ActionResult BlockCustomer(int user_id, int BlockDuration)
        {
            var result = false;
            var customer_selected = db.Customers.SingleOrDefault(x => x.userId == user_id);
            if (customer_selected != null)
            {
                if (BlockDuration != 0)
                {
                    History_OfBlock HB = new History_OfBlock
                    {
                        customer_id = customer_selected.Id,
                        block_duration = BlockDuration,
                        end_block = @DateTime.Now.AddDays(BlockDuration)
                    };
                    db.History_OfBlock.Add(HB);
                    db.SaveChanges();

                    customer_selected.Isblocked = db.History_OfBlock.Max(c => c.Id);
                }
                else {

                    customer_selected.Isblocked = 0;
                }
                try {
                    db.SaveChanges();
                }
                catch
                {
                    //whdyhb
                }
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
       
        /************************************************************************************************/
       public ActionResult search_customer(string search_text)
        {
            var roles_db = db.Roles.ToList();
            var users_db = db.Users.Where(x => (x.Address.Contains(search_text) ||
                                            x.Email.Contains(search_text) ||
                                            x.Name.Contains(search_text) ||
                                            x.Phone.Contains(search_text)) &&
                                            x.RoleTypeId == 3

            ).ToList();

            var historyofblock_db = db.History_OfBlock.ToList();
            var customers_db = db.Customers.ToList();
            UsersRoles ucr = new UsersRoles
            {
                users = users_db,
                customers = customers_db,
                roles = roles_db,
                historyofblock = historyofblock_db
            };
            return View(ucr);

             

            //return PartialView("search_customer", ucr);


        }
        /************************************************************************************************/
        public ActionResult show_report()
        {
            var categories_db = db.Categories.ToList();
            var cars_db = db.Cars.ToList();
            var customers_db = db.Customers.ToList();
            var HistiryOfRent_db = db.HistiryOfRent.ToList();
            CarCustomerCategoryHistoryOfRent cuch = new CarCustomerCategoryHistoryOfRent
            {
                cars = cars_db,
                customers = customers_db,
                categories = categories_db,
                histories = HistiryOfRent_db
            };
            return View(cuch);

        }
    }
}

OnlineCarRentalSystem/OnlineCarRentalSystem/Controllers/CarController.cs
using OnlineCarRentalSystem.Models;
using OnlineCarRentalSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineCarRentalSystem.Controllers
{
    public class CarController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        [HttpGet]
        public ActionResult add_car()
        {
            var categories_db = db.Categories.ToList();
            CarCategory cc = new CarCategory
            {
                categories = categories_db

            };
            return PartialView(cc);
        }
        /******************************************************************************/
        [HttpPost]
        public ActionResult Image_File_Name(HttpPostedFileBase upload)
        {
            var result = false;
            if (upload != null)
            {
                string path = Path.Combine(Server.MapPath("~/uploads/car"), upload.FileName);
                upload.SaveAs(path);
                ImageUploaded.image_file_name = upload.FileName;
                result = true;

            }
            else
                ImageUploaded.image_file_name = null;

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /******************************************************************************/
        [HttpPost]
        public ActionResult add_car(CarCategory cc)
        {
            var result = false;
            if (ModelState.IsValid)
            {

                cc.car.Image = ImageUploaded.image_file_name;
                db.Cars.Add(cc.car);
                db.SaveChanges();
                result = true;

            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        /*******************************************************************************************/
        
        public ActionResult retrieve_cars(int user_role_id)
        {
            var cars_db = db.Cars.ToList();
            var categories_db = db.Categories.ToList();
            CarsCategory cc = new CarsCategory
            {
                categories = categories_db,
                cars = cars_db,
                UserRoleId=user_role_id
            };
            return View(cc);
        }
        /*******************************************************************************************/
        [HttpGet]
        public ActionResult edit_car(int id)
        {

            var car_selected = db.Cars.SingleOrDefault(x => x.Id == id);
            if (car_selected == null)
            {
                return View("NotFound");
            }

            var categories_db = db.Categories.ToList();
            CarCategory cc = new CarCategory
            {
                categories = categories_db,
                car = car_selected
            };
            return PartialView(cc);

        }
        /*******************************************************************************************/
        [HttpPost]
        public ActionResult edit_car(CarCategory cc)
        {
            var result = false;
            if (ModelState.IsValid)
            {

                var car_db = db.Cars.SingleOrDefault(c => c.Id == cc.car.Id);
                if (ImageUploaded.image_file_name != null)
                {
                    string old_image = Path.Combine(Server.MapPath("~/uploads/car"), car_db.Image);
                    System.IO.File.Delete(old_image);
                    car_db.Image = ImageUploaded.image_file_name;
                }
                else

                    car_db.car_category_id = cc.car.car_category_id;
                car_db.Model = cc.car.Model;
                car_db.Color = cc.car.Color;
                car_db.NumberOfChair = cc.car.NumberOfChair;
                car_db.PriceOfRent = cc.car.PriceOfRent;

                db.SaveChanges();
                result = true;

            }

            return Json(result, JsonRequestBehavior.AllowGet);

        }
        /*******************************************************************************************/
        [HttpPost]
        public ActionResult delete_car(int id)
        {
            var result = false;
            var car_deleted = db.Cars.SingleOrDefault(x => x.Id == id);
            if (car_deleted != null)
            {
                string old_image = Path.Combine(Server.MapPath("~/uploads/car"), car_deleted.Image);
                System.IO.File.Delete(old_image);
                db.Cars.Remove(car_deleted);

                db.SaveChanges();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        /*******************************************************************************************/
        [HttpPost]
        public ActionResult transform_car_state(int id)
        {
            var result = 0;
            var car_selected = db.Cars.SingleOrDefault(x => x.Id == id);
            if (car_selected != null)
            {
                if (car_selected.IsAvialable)
                {
                    car_selected.IsAvialable = false;

                }
                else
                {
                    car_selected.IsAvialable = true;
                    result = 1;
                }
                db.SaveChanges();

            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

OnlineCarRentalSystem/OnlineCarRentalSystem/Controllers/UserController.cs
using OnlineCarRentalSystem.Models;
using OnlineCarRentalSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineCarRentalSystem.Controllers
{
    public class UserController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var user_from_session = get_login_user();             
            return View(user_from_session);
        }
        /******************************************************************************************/
        [HttpPost]
        public ActionResult Index(User user_update_profile)
        {
            var result = false;
            
            var user_selected = db.Users.SingleOrDefault(x => x.Id.Equals(user_update_profile.Id));
            if (user_selected != null)
            {

                user_selected.Phone = user_update_profile.Phone;
                user_selected.Email = user_update_profile.Email;
                user_selected.Address = user_update_profile.Address;
               
                if (ImageUploaded.image_file_name != null)
                {
                    string old_image = Path.Combine(Server.MapPath("~/uploads/car"), user_selected.Image);
                    System.IO.File.Delete(old_image);
                    user_selected.Image = ImageUploaded.image_file_name;
                }
                if (user_update_profile.Password != null)
                {
                    user_selected.Password = user_update_profile.Password;
                }
                db.SaveChanges();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        /*******************************************************************************************/
     public User get_login_user()
        {
            var login_user_id = (Int32.Parse(Session["UserId"].ToString()));
            var user_from_session = db.Users.SingleOrDefault(x => x.Id.Equals(login_user_id));
            return user_from_session;
        }
        /*******************************************************************************************/
        [HttpPost]
        public ActionResult Image_Profile_Name(HttpPostedFileBase upload)
        {
            var result = false;
            if (upload != null)
            {
                string path = Path.Combine(Server.MapPath("~/uploads/user"), upload.FileName);
                upload.SaveAs(path);
                ImageUploaded.image_file_name = upload.FileName;
                result = true;

            }
            else
                ImageUploaded.image_file_name = null;

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        /************************************************************************************************/
        public ActionResult search(string search_text,int UserRoleId)
        {

            var result = db.Cars.Where(x => x.Color.Contains(search_text) ||
                                            x.Model.Equals(search_text) ||
                                            x.NumberOfChair.ToString().Equals(search_text) ||
                                            x.PriceOfRent.ToString().Equals(search_text) ||
                                            x.IsAvialable.ToString().Equals(search_text)

            ).ToList();

           
            var model = db.Categories.ToList();
          
            CarsCategory cc = new CarsCategory
            {
                categories =model,
                cars = result,
                UserRoleId=UserRoleId
            };

            return PartialView("partial_search", cc);


        }
       
    }
}

OnlineCarRentalSystem/OnlineCarRentalSystem/Views/Shared/NotFound.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    @Styles.Render("~/Content/NotFound.css")
   


</head>
<body>
    @{
        ViewBag.Title = "NotFound";
        
    }

    <div class="page-404">
        <p class="text-404">404</p>

        <h2>Error Occured !</h2>
        <p>
            Something went wrong or that page doesn’t exist yet. <br>
        </p>
    </div>

</body>
</html>>

OnlineCarRentalSystem/OnlineCarRentalSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/NotFound.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/file.css")
    @Styles.Render("~/Content/style.css")
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cars for rent", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    
                        <li>
                            <button type="button" onclick="Registration_form_modal()" class="btn btn-primary">Registration</button>
                    </li>
                        <li>
                            <button type="button" onclick="login_form_modal()" class="btn btn-primary">Log In</button>
                         </li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="navbar navbar-fixed-bottom">
            <p>&copy; @DateTime.Now.Year - Online Car Rental System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/circle-progress.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineCarRentalSystem/OnlineCarRentalSystem/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/NotFound.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/file.css")
    @Styles.Render("~/Content/style.css")
    @Styles.Render("~/Content/style_cat.css")
    @Styles.Render("~/Content/profile_style.css")
</head>
<body class="">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cars for Rent", "Index", "Home", new { area = "" }, new { @class = "navbar-brand logo" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                   @if (Session["UserRoleId"].Equals(1))
                   {
                    <li>@Html.ActionLink("Profile", "Index", "User")</li>

                        <li>@Html.ActionLink("Manage Cars", "retrieve_cars", "Car", new { user_role_id = 1 }, null)</li>
                        <li>@Html.ActionLink("Add Category", "add_category", "Category")</li>
                        <li>@Html.ActionLink("Manage Categories", "retrieve_categories", "Category")</li>
                        <li>@Html.ActionLink("Manage Users", "retrieve_users", "Admin", new { user_role_id = 1 }, null)</li>
                        <li>@Html.ActionLink("Show Report", "show_report", "Admin")</li>

                   }
                /****************************************************************/
                    else if (Session["UserRoleId"].Equals(2))
                    {
                        <li>@Html.ActionLink("Profile", "Index", "User")</li>

                        <li>@Html.ActionLink("Manage Cars", "retrieve_cars", "Car", new { user_role_id = 2 }, null)</li>
                        <li>@Html.ActionLink("Add Category", "add_category", "Category")</li>
                        <li>@Html.ActionLink("Manage Categories", "retrieve_categories", "Category")</li>
                        <li>@Html.ActionLink("Manage Customers", "retrieve_users", "Admin", new { user_role_id = 2 }, null)</li>

                    }
                    /****************************************************************/
                    else if (Session["UserRoleId"].Equals(3))
                    {
                    <li>@Html.ActionLink("Show Cars", "retrieve_cars", "Car", new { user_role_id = 3},null)</li>
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                @if (Session["UserId"] != null)
                {
                    <li>@Html.ActionLink("Welcome : "+ Session["UserName"], "", "")</li>
                    <li>@Html.ActionLink("Log out", "Index", "Home")</li>
                }
                else
                    {
                    <li>@Html.ActionLink("Registar", "Registration", "Home")</li>
                    <li>@Html.ActionLink("Log in", "UserLogin", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content ">

        @RenderBody()

        <hr />
     
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
   
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/circle-progress.min.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $('.dropdown-toggle span').on('click', function () {
                $('.appear').fadeIn(500);
            });

            $('body').css('backgroundColor', '#EEE');
        });
    </script>

</body>
</html>